Repository memeLab/Jandig, pull requests merged in 2021-06, with the labels that each got.

#381 [REVIEW] 378 - Exhibit url error translation
  locale/pt_BR/LC_MESSAGES/django.po
  src/ARte/users/jinja2/users/exhibit-create.jinja2
Labels: interface text

#389 [REVIEW] 377-moving-form-field
  locale/pt_BR/LC_MESSAGES/django.po
  src/ARte/users/jinja2/users/edit-object.jinja2
  src/ARte/users/jinja2/users/upload.jinja2
  src/ARte/users/static/css/upload.css
Labels: bug

#394 [REVIEW] 392-titles-django-admin
  src/ARte/users/models.py
Labels: enhancement, feature

#402 [REVIEW] 399 - using http without decorators
  src/ARte/core/views.py
  src/ARte/users/views.py
Labels: code, enhancement, security

#404 [REVIEW] 403 - variables shadowing builtins
  src/ARte/core/views.py
  src/ARte/users/views.py
Labels: code, enhancement

#405 [REVIEW] 398 - Fix unavailable local smtp envs
  docker/docker-compose.yml
  src/.envs/.dev_deploy
  src/.envs/.prod_deploy
  src/.envs/.smtp
  src/.envs/.staging_deploy
  src/ARte/users/services/email_service.py
Labels: bug

#414 [REVIEW] 314 - missing login error messages
  src/ARte/users/jinja2/users/login.jinja2
Labels: CMS, enhancement, user

#417 [REVIEW] Fix hash vulnerability when generating password recovery
  src/ARte/users/jinja2/users/login.jinja2
  src/ARte/users/services/encrypt_service.py
Labels: security

#397 [REVIEW] 396 - response used before defined
  src/ARte/users/tests.py
Labels: bug

#415 [REVIEW] 391 - Issue template to refactoring proposal
  .github/ISSUE_TEMPLATE/refactoring.md
Labels: code, enhancement
