Repository memeLab/Jandig, pull requests merged in 2021-03, with the labels that each got.

#385 [REVIEW] 375 - Add new issue template to feature request
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#387 [REVIEW] 307 - Creation edition page of artwork.
  locale/pt_BR/LC_MESSAGES/django.po
  src/ARte/users/jinja2/users/artwork-edit.jinja2
  src/ARte/users/jinja2/users/exhibit-edit.jinja2
  src/ARte/users/views.py
Labels: bug

#382 [REVIEW] 374 - Move SMTP credentials to external environment variable
  src/.envs/.dev_deploy
  src/.envs/.prod_deploy
  src/.envs/.staging_deploy
  src/ARte/users/services/email_service.py
Labels: bug, enhancement
