Repository memeLab/Jandig, pull requests merged in 2022-10, with the labels that each got.

#472 [REVIEW] 468 - Create an Django REST API viewset that supports List and Retrieve for Markers
  poetry.lock
  pyproject.toml
  src/ARte/config/settings.py
  src/ARte/core/jinja2/core/collection.jinja2
  src/ARte/core/renderers.py
  src/ARte/core/serializers/__init__.py
  src/ARte/core/serializers/markers.py
  src/ARte/core/urls.py
  src/ARte/core/views/__init__.py
  src/ARte/core/views/static_views.py
  src/ARte/core/views/v1/__init__.py
  src/ARte/core/views/v1/markers.py
  src/ARte/core/views/views.py
  src/ARte/users/jinja2/users/components/elements-modal.jinja2
Labels: enhancement, feature

#460 [REVIEW] 457 - Configure development pipeline
  .github/workflows/ci.yml
  .github/workflows/dependencies.yml
  .github/workflows/push.yml
  docker-compose.ci.yml
  poetry.lock
  src/config/jinja2.py
  src/config/settings.py
  src/config/urls.py
  src/config/wait_db.py
  src/config/wsgi.py
  src/core/admin.py
  src/core/apps.py
  src/core/forms.py
  src/core/helpers.py
  src/core/models.py
  src/core/routes.py
  src/core/views/static_views.py
  src/core/views/views.py
  src/manage.py
  src/users/admin.py
  src/users/apps.py
  src/users/choices.py
  src/users/factory.py
  src/users/forms.py
  src/users/models.py
  src/users/services/email_service.py
  src/users/services/encrypt_service.py
  src/users/services/user_service.py
  src/users/urls.py
  src/users/views.py
Labels: CI/CD, architecture, feature

#467 Feature/462 help installation
  docs/images/installation-guide-createFile.png
  docs/images/installation-guide-duplicate-dependency.png
  docs/images/installation-guide-expected-window.png
  docs/images/installation-guide-migration.png
  docs/images/installation-guide-minio.png
  docs/images/installation-guide-terminal-expected.png
  docs/installation-guide.md
Labels: documentation
